### ISSUE TITLE
npm 怎么打deb的包

### ISSUE THREAD

**Issue by lexusking** [eNkru/electron-wechat#4]
在linux下执行npm run dist:linux,会报如下错误 
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/home/liuwx/temp/electron-wechat/node_modules/electron-builder/out/cli/cli.js:77:16)
    at Object.args [as handler] (/home/liuwx/temp/electron-wechat/node_modules/electron-builder/src/cli/cli.ts:43:3)
    at Object.runCommand (/home/liuwx/temp/electron-wechat/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/liuwx/temp/electron-wechat/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/liuwx/temp/electron-wechat/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/liuwx/temp/electron-wechat/node_modules/electron-builder/src/cli/cli.ts:25:28)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-wechat@0.1.1 dist:linux: `electron-builder --linux AppImage`
npm ERR! Exit status 1

看了package.json, 里面的dist:linux 只会打  AppImage的包 ,想知道你是怎么打deb的包的?后续只需要更新代码自己在本地打包就可以使用最新版本了, 不需要每次都下载 release包(下载速度有点慢)

**Comment by lexusking** [comment]
花了点时间研究了下 npm 打包,已经自行解决了.

**Comment by eNkru** [comment]
解决方案

把 electron-builder --linux AppImage 改称 electron-builder --linux deb 就可以了

我的开发环境是arch，花时间BUILD DEB包，就没加进去。release的时候会有deb
